#!/usr/bin/env node
"use strict";

var login = require('./ftp_login.json');
var FtpDeploy = require('ftp-deploy');
var ftpDeploy = new FtpDeploy();

var config = {
    username: login.user,
    password: login.pass,
    host: "ftp.aryweb.nl",
    port: 21,
    localRoot: __dirname + "/public",
    remoteRoot: "/domains/aryweb.nl/public_html",
    exclude: ['.git', '.idea', 'tmp/*', '.gitignore']
};

ftpDeploy.on('uploading', function(data) {
    console.log(data);
});

ftpDeploy.on('error', function(err) {
    console.log(err);
});

ftpDeploy.deploy(config, function(err) {
    if (err) console.log(err);
    else console.log('finished');
});
