#! /bin/bash

DEST="domains/aryweb.nl/public_html/"
SCRIPT="deploy_ftp"

cat ./ftp_login > deploy_ftp

find public -type d | awk "{ \
	str = gensub(/public\//, \"$DEST\", \$1); \
	print \"mkdir \" str
}" >> "$SCRIPT"

find public -type f | awk "{ \
	str = gensub(/public\//, \"$DEST\", \$1); \
	print \"put \" \$1 \" \" str
}" >> "$SCRIPT"

echo "quit" >> "$SCRIPT"
